# Generated by Django 4.2.17 on 2025-01-02 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_client_compani_name_alter_client_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='Наименование')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Тара',
                'verbose_name_plural': 'Тара',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.packing', verbose_name='Тара')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оприходование',
                'verbose_name_plural': 'Оприходование',
            },
        ),
        migrations.CreateModel(
            name='Extradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('balance_storage', models.IntegerField(verbose_name='Остаток')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client', verbose_name='Клиент')),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.packing', verbose_name='Тара')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выдача',
                'verbose_name_plural': 'Выдача',
            },
        ),
        migrations.CreateModel(
            name='Comeback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client', verbose_name='Клиент')),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.packing', verbose_name='Тара')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Возврат',
                'verbose_name_plural': 'Возврат',
            },
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.packing', verbose_name='Тара')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Списание',
                'verbose_name_plural': 'Списание',
            },
        ),
    ]
