# Generated by Django 4.2.19 on 2025-02-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packing',
            options={'verbose_name': 'тару', 'verbose_name_plural': 'Тара'},
        ),
        migrations.AddField(
            model_name='register',
            name='operation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='packing',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='в наличии'),
        ),
    ]
