# Generated by Django 4.2.19 on 2025-02-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_packing_options_register_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='operation',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
